name = "[REDACTED]"
author = "BlueDaisy84 and mounderfod"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f0e2d37e5e0602848086f8bdc92582b07c8e13b433233c3e863d209c6d3938e"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
