name = "[REDACTED]"
author = "BlueDaisy84 and mounderfod"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55e93d9f8b5dd99ed15a4ff30d841d15eb0b881843edc7f34961738331693797"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
